### ISSUE TITLE
Perl error in the $seqHash

### ISSUE THREAD

**Issue by evolgenomology** [AlexGa/Phylostratigraphy#1]
Hi there,

I am getting the following error trying to run the program:

```
Type of arg 1 to keys must be hash (not private variable) at ../Phylostratigraphy/createPSmap.pl line 196, near "$seqHash;"
Execution of ../Phylostratigraphy/createPSmap.pl aborted due to compilation errors.
```.
I thought it might be the headers of my file. I have:
```>ANAN_ju_g16.t1  | [Arobeloides nanus] | [Eukaryota; Opisthokonta; Metazoa; Eumetazoa; Bilateria; Protostomia; Ecdysozoa; Nematoda; Chromadorea; Rhabditida; Cephaloboidea; Cephalobidae; Acrobeloides]
SKLVEFGDTIFIALRKRPLTFLHCYHHCSVLIYTFHSGAEHLASGRWFMWMNFIAHSVMYTYFCAVSAGIKVPRKLAKCVTLIQITQMILGIGVSLSVFA
IKSLTSWRCHQSYTNLYLSFFIYVSYAILFIRFFINAYSPNKKVIESDKQK
```.
But I am not sure. Would be great if you could look into this.

Cheers

Philipp

**Comment by evolgenomology** [comment]
OK, I think the problem lies here. Output from perl -d:

``````
BEGIN not safe after errors--compilation aborted at /usr/share/perl5/Carp/Heavy.pm line 11.
Compilation failed in require at /usr/share/perl5/Carp.pm line 33.
```.

I am running it from another machine:
```perl createPSmap.pl --organism /cluster_space/Ananus-phylostrat/Ananus.run7-j3-i3.SB.scaffolds.filtered.aug2.ju765.out2.phylostra.faa --database /cluster_space/Ananus-phylostrat/phyloBlastDB.fa --prefix ANAN-ju_BlastPlus_PS_map --seqOffset 50  --evalue 1e-5 --threads 20 --blastPlus
keys on reference is experimental at createPSmap.pl line 196.```.

``````

**Comment by evolgenomology** [comment]
Further downstream I am now getting:

``````
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
        at java.lang.Class.forName0(java.base@9-ea/Native Method)
        at java.lang.Class.forName(java.base@9-ea/Class.java:374)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
        at java.net.URLClassLoader.findClass(java.base@9-ea/URLClassLoader.java:388)
        at java.lang.ClassLoader.loadClass(java.base@9-ea/ClassLoader.java:486)
        at java.lang.ClassLoader.loadClass(java.base@9-ea/ClassLoader.java:419)
        ... 3 more
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
        at java.lang.Class.forName0(java.base@9-ea/Native Method)
        at java.lang.Class.forName(java.base@9-ea/Class.java:374)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
        at java.net.URLClassLoader.findClass(java.base@9-ea/URLClassLoader.java:388)
        at java.lang.ClassLoader.loadClass(java.base@9-ea/ClassLoader.java:486)
        at java.lang.ClassLoader.loadClass(java.base@9-ea/ClassLoader.java:419)
        ... 3 more
```.

``````

**Comment by AlexGa** [comment]
Thanks for reporting the bug and sorry, for the really really late answer. The hash reference in line 196 was not used in a proper way. Now it should work without compilation errors.
